# Generated by Django 3.2.13 on 2022-06-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_alter_boost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='drinkCount',
            field=models.IntegerField(default=0),
        ),
    ]
