# Generated by Django 3.2.13 on 2022-06-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_alter_boost_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='drinkCount',
        ),
    ]
